In [ ]:
# 파이썬 활용해서 내가 원하는 데이터 수집, 전처리, 표/시각화/그래프

# -> 주어진 데이터에 대한 핸들링
# + pandas (제일 기본 패키지!)
# + numpy (외부 패키지!)

# 전제 조건 : 패키지가 다운 받아져야함.
# colab, anaconda 는 이미 다운되어 있음.
# colab 은 최신은 아님. anaconda 와 다를 때 있고 -> 버전 이슈 (갑자기 colab에서 업데이트하면 코드가 안돌아갈 수 있음)



### numby

데이터를 처리하는 가장 파있너에서 기본이 되는 패키지
-> numerical python : 수치 연산
+ pandas, scikit-learn, tf/pytorch

-> numpy 는 가장 대표적인 자료형 array 자료형을 개발!

In [2]:
import numpy as np  # numpy의 기능을 부를 때 np.~~
import pandas as pd # pandas~~ pd.~~

# 사람들이 개발하고 배포한 패키지들을 활용을 하니
# 내가 지금 사용하는 버전을 꼭 체크!
# --> 버전에 따라서 기능의 변화가 있음.

pd.__version__ 
# --> 2024.04.08 년 기준 ) 2.1.4
# 앞으로는 최소한 pandas 2.대 코드를 작성할 것.

np.__version__
# --> 2024.04.08 년 기준 ) 1.26.4

'1.26.4'

In [5]:
# m1) 생 파이썬 : 꾸역꾸역 돌리기
a= [100,200,300,400,500]
b=[]
for i in a :
    b.append(i+10)
print(b)

# m1) 생 파이썬 업글 : 리스트 컴프리핸션
[i+10 for i in a] 

### for 문을 사용해 롤링해서 개별 원소에 접근하는 수밖에 없음!

[110, 210, 310, 410, 510]


[110, 210, 310, 410, 510]

In [9]:
# m3) numpy의 패키지를 활용해서 array 자료형을 사용하자!
# --> array는 벡터연산을 기본으로 하는 자료형!
# 내가 할 일만 정해주면,, 모든 원소에 일괄적용

a_arr = np.array(a)
a_arr #리스트라고 보이지만 array 라고 가공을 해놓은 거임. 내부적으로 벡터 연산이 가능함

array([100, 200, 300, 400, 500])

In [11]:
a_arr +10  # 벡터형식이기 때문에 일괄 연산이 가능함.

array([110, 210, 310, 410, 510])

### 예시

In [12]:
# ex)
x=[1,2,3,4,5]
y=[10,20,30,40,50]
#(1+10, 2+20, 3+30, 4+40, 5+50)
# x+y 벡터적인 표현 (선대 표현 ㅣ 수식적인 표현)

In [14]:
# m1-1) 쌩 파이썬으로
z=[]
for i in range(len(x)):
    z.append( x[i] +y[i])
z

[11, 22, 33, 44, 55]

In [15]:
# m1-2) numpy 로
x_arr = np.array(x)
y_arr = np.array(y)

x_arr + y_arr

array([11, 22, 33, 44, 55])

In [16]:
# numpy는 사용이 수치연산을 위해 하는 것이라
# 통일성 있게 사용해야함
# 그래야 원하는대로 동작을 한다는 의미

# 생 파이썬의 리스트 : 값들을 모아둘 수 있음. 숫자, 문자, 리스트, etd, 차원에 대한 정보는 없음.
# numpy는 array : 값들을 모아둘 수 있음. 숫자, 문자, 리스트 etc. +오와 열, 종류가 맞으면 차원도 인식함.
#                                                               + 기능을 부여하면, 기본적으로 모든 값에 일정

In [21]:
arr = [1,2,3,["a","b",[1,2,3]]]
test_arr = np.array(arr)
# type(test_arr)
# test_arr.dtype

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [ ]:
test_arr.dtype

In [22]:
# arrary 사용시 형식을 딱 맞춰서 사용하는 게 일반적
test_arr2 = np.array([1,2,3,4,5])
test_arr2

array([1, 2, 3, 4, 5])

In [24]:
# 1) 이 array의 값들의 자료형
# 2) 이 arrar의 차원에 대한 정보
# 3) d어떤 모양으로 이루어져 있는지

In [26]:
test_arr2.dtype

dtype('int32')

In [27]:
test_arr2+1 #연산 가능!

array([2, 3, 4, 5, 6])

In [28]:
# 참고) 2차원으로 하게 되면,
test = [
    [1,2,3],
    [4,5,6]
]
test

[[1, 2, 3], [4, 5, 6]]

In [29]:
test_arr = np.array(test)
test_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
test_arr.dtype

dtype('int32')

In [31]:
test_arr.shape

(2, 3)

In [33]:
len(test_arr) # 2차원의 경우에는 가로줄의 수

2

In [35]:
test_arr[1,2] #배열로 접근 가능함. test[1,2] 에러남 test에서는 test[1][2] 처럼 인덱스로 접근

6

In [42]:
a_arr = np.array(a)
a_arr[0]
a[:3]

[100, 200, 300]

In [41]:
arr[[0,1,3]] # - > 인덱스 자리에 내가 보고자 하는 것들을 덩어리로 던질 수 있음.
#              - > 인덱스 자리에 보고자 하는 값들 리스트도 들어 있음
# => numpy 를 기반을 하는 값의 접근에 그냥 보고자하는 거 덩어리

TypeError: list indices must be integers or slices, not list

In [43]:
# 참고) 강제로 값의 타입 변경
b=[1,2,3]
b_arr = np.array(b)
b_arr.dtype

dtype('int32')

In [44]:
# dtype에는 numpy가 정한 메뉴얼상 정한 값의 타입을 지정할 수 있음.
# -> 훨씬 많은 타입이 있음.
b_arr = np.array(b, dtype=np.string_)
b_arr.dtype

dtype('S1')

In [46]:
# 데이터를 불러놓고, 원하는 형이 아니여서 변경할 때.
# -> 강제적으로 내부 데이터 타입 변경!
b_arr.astype(np.float64)

array([1., 2., 3.])

In [47]:
b_arr # --> astype은 재할당을 해야함. 기존 데이터는 바뀌지 않는다.

array([b'1', b'2', b'3'], dtype='|S1')

## numpy 인덱싱 연습

In [48]:
# 주어진 2차원 array에 대해서 생성할 때
# m1) 그냥 직접 값들을 다 작성하는 방법
# m2) 벡터연산을 활용하는 방법 : 규칙

m=[
    [0,1,2,3,4,5],
    [10,11,12,13,14,15],
    [20,21,22,23,24,25],
    [30,31,32,33,34,35],
    [40,41,42,43,44,45],
    [50,51,52,53,54,55],
]
m

[[0, 1, 2, 3, 4, 5],
 [10, 11, 12, 13, 14, 15],
 [20, 21, 22, 23, 24, 25],
 [30, 31, 32, 33, 34, 35],
 [40, 41, 42, 43, 44, 45],
 [50, 51, 52, 53, 54, 55]]

In [51]:
list(range(0,6,1)) #생 파이썬

[0, 1, 2, 3, 4, 5]

In [57]:
# 앞에 시작하는 컬럼 벡터 0, 10, 20... :2D
np.arange(0, 51, 10)[:,np.newaxis] # 가로줄은 처음부터 끝까지. 세로줄은 축으로


array([[ 0],
       [10],
       [20],
       [30],
       [40],
       [50]])

In [63]:
a = np.arange(0, 51, 10)[:,np.newaxis] + np.arange(0,6,1)
a
#벡터 연상을 통해 규칙이 있는 2d를 만들 수 있다.

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [64]:
print(a.dtype)
print(a.ndim)
print(a.shape)

int32
2
(6, 6)


In [66]:
#### 원하는 값에 대한 2차원에 대한 접근 연습!
# 예) 12값에 대한 접근
# 생파이썬 - > 순차적 접근
a[1][2]

12

In [67]:
# numpy 바로 접근이 가능함!
a[1,2]

12

In [68]:
# 정리) numpy 에서 2D 차원 데이터의 값의 접근 방식!
# 1) 생 파이썬 리스트 처럼 : 가로 접근 후에 -> 새로 접근하는 a[가로][세로] 
# 2) 원하는 포지션을 직접 지정
# -> 가로 어디, 세로 어디
# a[가로 , 세로]

In [72]:
# Q) 처음 줄 2,3 접근 방식은?
a[0][2:4]

array([2, 3])

In [73]:
a[0,2:4]

array([2, 3])

In [74]:
# Q) 2번째 세로줄에 대한 접근! 
a[:,2]

array([ 2, 12, 22, 32, 42, 52])

In [76]:
# 연습 20,22,24, 40, 42,44 접근
a[2::2,::2]

array([[20, 22, 24],
       [40, 42, 44]])

In [77]:
# 연습 44, 45, 54,55 접근
a[4:6,4:6]

array([[44, 45],
       [54, 55]])

In [ ]:
### 중요!
# 불리언 인덱싱!
# 인데싱 : 정수, 슬라이싱, 리스트(주의) : 가로,세로 독립적
#          + 조건식이 들어감
# 불리언 인덱싱  :numpy의 array의 인덱스 자리에 조건식이 들어간다.
# --> 필터링! (조건 검색!) : sql where having~
#     pandas에서 데이터에 필터링을 할 때 필터링한 조건을 인덱스 자리에 작성을 함!
# + 벡터 연산을 이해를 해야 함!



In [79]:
test_arr = np.arange(10)
test_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
# 예) 5보다 작은 값들을 추리고 싶다. --> 필터링, where
test_arr <5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [82]:
test_arr[test_arr<5]
# 인덱스 자리에 조건식이 들어가서 모든 원소에 해당하는 조건에 맞는 여부를 물어보고(벡터 연산)
# 인덱스에 T/F가 T에 해당하는 값만 출력하는데, : 필터링!

array([0, 1, 2, 3, 4])

In [87]:
test_list = list(test_arr)
sum(test_list)

45

In [88]:
test_arr.sum() # 이미 패키지가 만든 기능이 있따면 그 기능을 쓰는 것을 추천함.

45

## pandas

In [89]:

# 생성1) 파이썬 리스트
stock_price_list = [10000, 10300, 9900, 10500, 11000]
# 생성2) numpy -> array
stock_price_arr = np.array(stock_price_list)
# 생성3) 1차워 series
stock_price_Series = pd.Series(stock_price_list)

In [91]:
print(stock_price_list)
print(stock_price_arr)
print(stock_price_Series)

[10000, 10300, 9900, 10500, 11000]
[10000 10300  9900 10500 11000]
0    10000
1    10300
2     9900
3    10500
4    11000
dtype: int64


In [92]:
# 1번 주식 가격에 대한 접근
print(stock_price_list[0])
print(stock_price_arr[0])
print(stock_price_Series[0])

10000
10000
10000


In [93]:
# 1~3번 주식 가격에 대한 접근
print(stock_price_list[0:4])
print(stock_price_arr[0:4])
print(stock_price_Series[0:4])

[10000, 10300, 9900, 10500]
[10000 10300  9900 10500]
0    10000
1    10300
2     9900
3    10500
dtype: int64


In [94]:
# 내가 보고자 하는 게 0번째 주가하고 4번째 주가만 보자
stock_price_list[[0,4]]

TypeError: list indices must be integers or slices, not list

In [95]:
stock_price_arr[[0,4]]

array([10000, 11000])

In [96]:
stock_price_Series[[0,4]]

0    10000
4    11000
dtype: int64

In [97]:
# 특별하게 하지 않으면, 그냥 값들만 모아둔 것이라서
# 정수인덱스는 태생적으로 가지게 됨!
stock_price_Series_index = pd.Series(
    # 데이터 값, 내가 원하는 인덱스 같이..
    data = [10000,10300,9900,10500,11000],
    index = ['2024-04-01','2024-04-02','2024-04-03','2024-04-04','2024-04-5']
) ## 똑같은 시리즌데 내가 지정한 index가 있으면 그걸로 지정해줌.
stock_price_Series_index

2024-04-01    10000
2024-04-02    10300
2024-04-03     9900
2024-04-04    10500
2024-04-5     11000
dtype: int64

In [98]:
stock_price_Series_index['2024-04-01']

10000

In [99]:
stock_price_Series_index[['2024-04-01','2024-04-02']] # 냅다 index 뭉탱이 던지기!!

2024-04-01    10000
2024-04-02    10300
dtype: int64

In [100]:
# 참고) 쌩파이썬의 dict 처럼 exact matching -> 공백, 대소문자, 오타 등에 유의를 해야함
stock_price_Series_index['2024-04-01']

10000

In [101]:
# numpy에 다가 + 내가 만든 인덱스를 핸들링 할 수 있는 기능 추가
# => numpy 의 대부분의 기능을 가지고 있음
# 불리언 인덱싱이 여기서도?
# 예) 주식 가격이 10000원이 넘는 데이터만 추려보자!

In [102]:
stock_price_Series_index[stock_price_Series_index>10000]

2024-04-02    10300
2024-04-04    10500
2024-04-5     11000
dtype: int64

In [ ]:
# 참고) dict 하고 상당히 유사하게 동작을 함! key+ values
# pandas index(정수, 내가 만든거) + value

In [103]:
stock_price_Series_index.index

Index(['2024-04-01', '2024-04-02', '2024-04-03', '2024-04-04', '2024-04-5'], dtype='object')

In [104]:
stock_price_Series_index.values

array([10000, 10300,  9900, 10500, 11000], dtype=int64)

In [ ]:
# 참고) 자료형이 파이썬의 dict는 key중심으로 체크
# 파이썬의 리스트는 value 중심으로 체크
# pandas 에서는? index! 값이 아니라!!!! 인덱스 중심!!!!!

In [ ]:
# 알아둘 사항 : 생파이썬의 dict <-> pandas SEries/DataFrame
# -> 데이터 수집 할 때 사용할 수 있음. 데이터 크롤링 할 때!

In [105]:
s_data = {"APPL" : 1000, "MS":2000,"TSLA":1500}
s_data

{'APPL': 1000, 'MS': 2000, 'TSLA': 1500}

In [106]:
s_data['APPL']

1000

In [107]:
s_data[0] ##정수 인덱스로 접근이 안됨.

KeyError: 0

In [108]:
s_data_Series = pd.Series(s_data)
s_data_Series

APPL    1000
MS      2000
TSLA    1500
dtype: int64

In [109]:
s_data_Series["APPL"]

1000

In [110]:
s_data_Series[0] #정수 인덱스로 접근 가능!

C:\Users\NT551XCJ\AppData\Local\Temp\ipykernel_4700\670982772.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s_data_Series[0]


1000

In [ ]:
# 참고) pandas 의 핵심은 => 내가 만든 인덱스!
# pandas의 기본적인 동작 방식 : 내가 만든 인덱스/ 인덱스!


In [113]:
s_data = {"APPL" : 1000, "MS":2000,"TSLA":1500}
s_1 = pd.Series(s_data)
ticker = ["GOOGLE","APPL","MS","META"]
s_2 = pd.Series(s_data, index = ticker)
s_2

GOOGLE       NaN
APPL      1000.0
MS        2000.0
META         NaN
dtype: float64

In [117]:
temp = s_1+ s_2
temp

APPL      2000.0
GOOGLE       NaN
META         NaN
MS        4000.0
TSLA         NaN
dtype: float64

In [ ]:
# s_1 : appl, ms, tsla
# s_2 : google, apple, ms, meta

# -> pandas 에서는 index 에 대해서 대충 처리하면, 원하지 않는 row가 생성됨.
# 그래서 결측치 데이터에 대한 처리가 중요!
# -> 자주 사용되는 메서드!
# .isnull(): 너 값이 결측값이냐? -> T/F
# .notnull(): 정상값이냐? -> T/F

# -> T/F에 따라서 원하는 조건의 값들만 필터링!
# + 불리언 인덱싱이랑 결합되는 부분이 있음

In [119]:
# 실제 받은 데이터에서 결측치들만 체크
# -> 빈 데이터들에 대해 확인할 때 사용!
temp[temp.isnull()]

# 정상적인 데이터만 보겠다!
temp[temp.notnull()]


APPL    2000.0
MS      4000.0
dtype: float64

In [ ]:
#위의 경우들이 FM 적으로 맞는 말인데
# 실제 데이터들을 처리하다보면, 더 단순 기능으로는 안 되는 것들
# NaN 처리가 되는 애들만 걸러주는 역할이..

""
None
# -> 코드적인 부분만이 아니라 실제 데이터들을 보면서
#     결측값에 대한 처리를 해야함.


In [120]:
# 기타) 
temp.ndim # 시리즈는 무조건 1차원


1

In [121]:
temp.shape #튜블로 나와서 접근하려면 temp.shape[0] 해야함

(5,)

In [122]:
len(temp) # tmep.shape[0]이랑 똑같음

5

In [123]:
temp.dtype

dtype('float64')

In [ ]:
# pandas 에서는 값에 대한 접근 방식 : FM 방법을 알아보겠음
# 기존의 방식) 인덱스 자리에 내가 원하는 것을 던지자!
#     -> 정수, 슬라이싱, 리스트 etc
#     + 내가 만든 거 , 내가 만든 걸로 슬라이싱, 리스트
#     + 조건식 기반의 불리언 인덱싱(필터링)

# 앞의 결론) series[대충 던지면 됨]

# 값이 많은 경우에는 FM 으로 해야 속도가 빠름!
# -> 생각보다 많이 차이가 남!



In [127]:
stock_price_Series_index = pd.Series(
    # 데이터 값, 내가 원하는 인덱스 같이..
    data = [10000,10300,9900,10500,11000],
    index = ['2024-04-01','2024-04-02','2024-04-03','2024-04-04','2024-04-5']
)

In [128]:
stock_price_Series_index[0]
# 비공식적으로 가능하나 데이터가 많으면 속도 차이남.

C:\Users\NT551XCJ\AppData\Local\Temp\ipykernel_4700\2592654350.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stock_price_Series_index[0]


10000

In [130]:
# 예 ) 정수 인덱스 0번째 접근 : FM
stock_price_Series_index.iat[0]

10000

In [131]:
stock_price_Series_index.iloc[0]
# 속도 -> [0] > iloc[0]> iat[0]

10000

In [137]:
# 예 ) 2024년 4월 4일 주식 가격은 얼마?
# --> 내가 만든 인덱스 & 1개 : at
stock_price_Series_index.at['2024-04-01']

10000

In [138]:
# 예) 0번째부터 4번째 날의 주식 데이터를 보여주세요.
stock_price_Series_index[:4]

2024-04-01    10000
2024-04-02    10300
2024-04-03     9900
2024-04-04    10500
dtype: int64

In [139]:
stock_price_Series_index.iloc[:4]

2024-04-01    10000
2024-04-02    10300
2024-04-03     9900
2024-04-04    10500
dtype: int64

In [140]:
# 예) 2024-04-02 부터 2024-04-04까지 주가데이터 보여주세요.
stock_price_Series_index['2024-04-02':'2024-04-04'] #비공식

2024-04-02    10300
2024-04-03     9900
2024-04-04    10500
dtype: int64

In [141]:
stock_price_Series_index.loc['2024-04-02':'2024-04-04'] #속도가 훨 빠름!!

2024-04-02    10300
2024-04-03     9900
2024-04-04    10500
dtype: int64

In [142]:
# 참고) 수치연산에 대한 기능도 있음 
stock_price_Series_index.sum()

51700

In [145]:
sum(stock_price_Series_index)

51700

In [143]:
stock_price_Series_index.count()

5

In [144]:
stock_price_Series_index.max()

11000