In [ ]:
# DL은 무조건 GPU 있어야 함
# T4로 세팅
# ML : scikit learn + pandas etc
# DL : TensorFlow & Keras 중심 (버전 1, 2는 완전 다름. 코드 수정 필요 : TF 는 2.X 참고 할 것!)
#   : pytorch 사용할 것! 다만 버전 이슈가 있음

# 조별 프로젝트 : 최신 1~2년으로 버전 세팅 맞추고 시작할 것.
# TF 중에서도 keras 모듈 사용이 가능함. -> keras 가 사용하기 편함

In [1]:
import numpy as np

In [3]:
# 01) 0차원 : 스칼라 ex) 3
# 코드로 표현하기
arr = np.array(10)

In [4]:
arr.shape

()

In [5]:
# () : 0차원임을 알 수 있음.
arr.ndim

0

1) 1차원 : 여러개의 스칼라 값을 일렬로 묶어둔 벡터  
  --> col-vector, row-vector  
  --> 10개를 1차원으로 묶을지, 100개를 1차원으로 묶을지, 개수를 고민해야한는 부분

In [6]:
arr = np.array([10])

In [7]:
arr.shape

(1,)

In [8]:
# 1차원임을 알 수 있음.
arr.ndim

1

In [9]:
# 1차원에 3개의 원소를 가지는 벡터
arr = np.array([1,2,3])

In [10]:
arr.shape

(3,)

2) 2차원 : Matrix  
  --> 가로, 세로에 대한 2차원 정보가 명확  
  --> 파이썬으로 간접적으로 표현하는 게 리스트에서 가로 세롤로 나옴

In [14]:
# 파이썬의 리스트로 2차원 간접표현
arr = np.array([
                [1,2,3],
                [4,5,6],
                [7,8,9]
            ])

In [15]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
arr.shape

(3, 3)

3) 3차원 Tensor  
  --> 컬러이미지 데이터 1장  
&nbsp;&nbsp;&nbsp;&nbsp;이미지 크기 : 2 by 3  
&nbsp;&nbsp;&nbsp;&nbsp;이미지의 채널(색상) : R/G/B  
  --> 컬러이미지 1장의 데이터는 3차원 데이터!  

In [22]:
arr = np.array(
    [
        [[1,2,3],
         [4,5,6]],
        [[7,8,9],
         [10,11,12]],
        [[12,13,14],
         [15,16,17]]
    ]
)
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [20]:
arr.shape

(3, 2, 3)

In [23]:
arr.ndim

3

TF  
colab 에서 GPU 세팅

In [24]:
import tensorflow as tf

In [26]:
tf.__version__ #참고 : 양쪽 언더바 2개
              # 갑자기 예고없이 버전을 바꾸는 경우가 있음;

'2.15.0'

TensorFlow 에서는 기본인 되는 자료형 : tensor  
python : list/ tuple
numpy : array(차원, 모양, 벡터연산) np.array  
TF : tensor(고차원의 연산, DL에 연동자료형)  
&emsp;tf.constant


In [27]:
#예) 파이썬 리스트 이요해서 1D tensor 로 변환
tf.constant([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [29]:
arr = np.array([1,2,3])
tf.constant(arr)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 3])>

In [31]:
tensor_1 = tf.constant(arr)
tensor_1.shape

TensorShape([3])

In [33]:
tensor_1.dtype

tf.int64

In [36]:
# 자료형이 중요함.
# 형 변환하면서 자료형을 지정!

t2= tf.constant([1,3,5], dtype = tf.float32)
t2

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 3., 5.], dtype=float32)>

In [37]:
# 예전에 arrary에서 비슷한 걸 했음
arr = np.array([1,2,3], dtype = np.float32)
arr

array([1., 2., 3.], dtype=float32)

In [38]:
tf.cast(t2, dtype = tf.int16)

<tf.Tensor: shape=(3,), dtype=int16, numpy=array([1, 3, 5], dtype=int16)>

In [39]:
arr.astype(np.int16)

array([1, 2, 3], dtype=int16)

In [40]:
# 서로 형 변환!
t2.numpy() #--> tf에서 array 값만 추출

array([1., 3., 5.], dtype=float32)

In [42]:
np.array(t2) # numpy의 자료형으로 강제 casting

array([1., 3., 5.], dtype=float32)

In [43]:
### TF 2.x + keras 모듈 기본 흐름

In [44]:
# 데이터 불러오기 + 수집한 것.

mnist = tf.keras.datasets.mnist
mnist

<module 'keras.api._v2.keras.datasets.mnist' from '/usr/local/lib/python3.10/dist-packages/keras/api/_v2/keras/datasets/mnist/__init__.py'>

In [45]:
# 참고) scikit-learn train_test_split

(X_train, y_train), (X_test, y_test) = mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [47]:
X_train.shape

(60000, 28, 28)

In [48]:
# 28 by 28 로 이루어진 이미지(흑백) 이 60000장 쌓여있는 3차원 데이터 셋

# input_layer : 1개 샘플로 설계! (28,28) 2D로 입력층 설계

# 참고) sikit-learn 의 ML로 한다면
#   -> 전체 60000장의 샘플을 무조건 2F
#     1장에 대한 28*28 2D - > 756 1차원 vactor 로 reshape 할거임
#     즉, 60000장에 대해 (60000, 756) 2D Matrix!

# DL : 그냥 쌓인대로 하면 됨
# 단, 1개 샘플 단위로 입력 레이어를 설계해야 함.

In [49]:
# 2) 전처리 : 정규화
X_train, X_test = X_train/255.0, X_test/255.0

# 0~255 까지의 개별 픽셀의 값들을 0~1 사이로 조정
# 딥러닝에서 값이 크면 학습이 잘 안됨. normalize 작업 필요

* 모델링 : 스스로 설계 + 남의 모델을 가져와서 튜닝  
&emsp;&emsp;--> 다른 사람들이나 최신 논문을 참조하면서 설계  

* TF의 keras 는 레고 조립하는 것처럼 쌓는 중심의 설계 방식!  
&emsp;&emsp;1) 쉽게 layer를 쌓아가는 방식 진행   
&emsp;&emsp;- feedback 구조 할 수 없음. 그냥 조립처럼 쌓으면 끝!!  
&emsp;&emsp;2) 함수처럼 설계를 in/out 방식으로 설계!(가독성은 안좋지만 feed back 구조가 다양하게 표현하기 용이함)  
&emsp;&emsp;--> 당분간 적층구조로만 코드 작성 예정

In [53]:
model = tf.keras.models.Sequential(
    [
        # 쌓는 구조의 방향 : 입력부터 -> 출력 방향으로 쌓는
        # 1번 층 : 기능은 입력을 받는 역할 input layer
              #  : 모양 학습할 데이터 1개 샘플을 받도록 설계
        # -> input layer의 input_shape이라는 파라미터도 퉁 침!
        tf.keras.layers.Flatten(input_shape =(28,28)),
        tf.keras.layers.Dense(128, activation= "relu"),

        # output layer : 모델의 목적 0-9까지, 10종류 분류
        tf.keras.layers.Dense(10, activation = "softmax")
    ]
)

model

In [54]:
# 3. 설계도 그린 모델을 학습시킬 방법
# compile 을 통해서 처리!
# 학부 방식 : 어떤 방법으로 최적의 w를 찾을 것인가 -> adam (GD)
# loss function :
# 모니터링 : 평가 -> metrics (여러개 지표 모니터링도 가능)

model.compile(
    optimizer = "Adam",
    loss = "sparse_categorical_crossentropy",
    metrics = ["accuracy"]
)

In [55]:
# 실제 데이터를 밀어 넣으면서 학습
model.fit(X_train, y_train, epochs  = 3)

Epoch 1/3
1875/1875 [==============================] - 7s 3ms/step - loss: 0.2644 - accuracy: 0.9238
Epoch 2/3
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1161 - accuracy: 0.9656
Epoch 3/3
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0792 - accuracy: 0.9764


In [56]:
model.evaluate(X_test, y_test)

313/313 [==============================] - 2s 5ms/step - loss: 0.0816 - accuracy: 0.9726


[0.08162202686071396, 0.972599983215332]

In [ ]:
# KNN 열심히 해도 이정도 안나오는데 DL 로 대충 1개만 쌓아도 0.97 이상 나옴
